services:
  api:
    build: .
    ports:
      - "8000:8000"

  streamlit:
    environment:
      - API_URL=http://api:8000
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: >
      bash -c "pip install streamlit requests shap==0.45.0 matplotlib joblib xgboost==2.1.0 scikit-learn numpy==1.26.4 pandas &&
               streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
    depends_on:
      - api
